@startuml
'https://plantuml.com/class-diagram

IndirizzoPersona <- Main

class IndirizzoPersona{
-nome:String
-cognome:String
-mail:String
-numero:String

+GetNome():String
+GetCognome():String
+GetMail():String
+GetNumero():String
+SetMail(nuova: String)
+SetNumber(nuovo: String)
+Equals(altro: IndirizzoPersona):Boolean
}

class Main{

}

@enduml